### ISSUE TITLE
The inference time

### ISSUE THREAD

**Issue by ardaduz** [magicleap/DELTAS#2]
Hello!
First of all, DELTAS is a great research and an easy-to-work-with code, so thank you.
I see in the paper that you report the forward pass time as ~90 milliseconds on a Titan RTX. I am using image size 320 x 240 for all of the upcoming values that I write here. Also I am using the faster SVD implementation that you share. I am trying to measure the inference time on a GTX 1060 and a GTX 1080Ti, but I can only measure ~530 milliseconds on 1060, and ~500 milliseconds on 1080Ti per prediction with batch size = 1. If I increase the batch size to 8, I can get around 200 milliseconds on 1080Ti per prediction. It might be possible to get 90 milliseconds per prediction with batch size 16 on a Titan RTX, unfortunately I can not test it. But I am not sure if it is meaningful to measure the inference time with batch size 16 anyway, in fact anything over 1 is pretty much always memory dependent and does not reflect the real frames per second value. The problem is, I am able to measure ~90 ms for MVDepthNet (this is close to what you report as ~60 ms), and ~380 ms for DPSNet with batch size = 1. And you clearly state that DPSNet is 2.5 times slower than DELTAS. 
Maybe I am making a mistake, could you please share the code or share some details on how you measure the inference time?

**Comment by sinhaayan87** [comment]
First author here. The inference times were measured with batch size 1 for all methods. I used the faster SVD library linked in the readme to measure inference times. I only tested on RTX gpus and cannot comment on GTX1080. Note I am no longer affiliated with Magic Leap, and hence cannot share additional code beyond what is already present in the code-base.
